// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Conexão direta (não-pooled) usada pelo CLI do Prisma (migrate deploy/
    // status, rodado via /api/admin/migrate). A app usa DATABASE_URL (pooled)
    // através do PrismaPg adapter em src/lib/db.ts — os dois são independentes
    // no Prisma 7, já que datasource.url aqui só vale para o CLI.
    url: process.env["DIRECT_URL"],
  },
});
